- name: install kvm and libvirt packages
  package:
    state: present
    pkg:
      - qemu-kvm
      - qemu-block-extra
      - libvirt-daemon
      - libvirt-daemon-system
      - libvirt-clients
      - libosinfo-bin
      - libguestfs-tools
      - virtinst
      - bridge-utils
      - netcat-openbsd
      - debootstrap
      - cdebootstrap
      - parted
      - kpartx
